version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
        SG_VERSION: $SG_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      TS_PASS: ${SSL_TS_PASS}
      KS_PASS: ${SSL_KS_PASS}
      CRT_NODE_NAME: ${SSL_CRT_NODE_NAME}
      CRT_CLIENT_NAME: ${SSL_CRT_CLIENT_NAME}
      CRT_CLIENT_DNAME: ${SSL_CRT_CLIENT_DNAME}
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
        ELK_FLAVOUR: $ELK_FLAVOUR
        SG_VERSION_KIBANA: $SG_VERSION_KIBANA
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
